### ISSUE TITLE
Signin failed

### ISSUE THREAD

**Issue by Samuelyip74** [Rainbow-CPaaS/Rainbow-Android-SDK-Samples#1]
Hi,  I clone the code and run the app in my Android device, tried to sign in with an account newly created in sandbox.  But I got an error that says Signin_failed: CONNECTION_WRONG_LOGIN_OR_PWD.

I can login via browser to the sandbox with the same email and password

Please advise what could be the problem?

**Comment by zucher** [comment]
Hi, did you change the target host to sandbox ?

Regards

**Comment by Samuelyip74** [comment]
Do I need to change?

Is already in the code.

private void attemptLogin() {
        final String email = m_loginView.getText().toString();
        final String password = m_passwordView.getText().toString();

        RainbowSdk.instance().connection().start(new StartResponseListener() {
            @Override
            public void onStartSucceeded() {
                RainbowSdk.instance().connection().signin(email, password, "sandbox.openrainbow.com", new SigninResponseListener() {
                    @Override
                    public void onSigninSucceeded() {
                        m_activity.runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                new ImNotificationMgr(m_activity);
                                m_activity.openConversationsTabFragment();
                                m_activity.unlockDrawer();
                            }
                        });
                    }
                    @Override
                    public void onRequestFailed(final RainbowSdk.ErrorCode errorCode, final String s) {
                        m_activity.runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                Toast.makeText(m_activity, "Signin failed: " + errorCode, Toast.LENGTH_SHORT).show();
                            }
                        });
                    }
                });
            }

            @Override
            public void onRequestFailed(RainbowSdk.ErrorCode errorCode, String err) {
                Log.getLogger().error(LOG_TAG, "SDK start failure !!!");
            }
        });

    }
}

**Comment by setyongr** [comment]
Is there any news about this issue? I also can't login to sandbox

**Comment by setyongr** [comment]
@Samuelyip74  You need to remove `applicationId` and `applicationSecret` from `Application`. Initialize the SDK like this `RainbowSdk.instance().initialize()`.

It's works for me

**Comment by Samuelyip74** [comment]
Thank you.  Got it resolved after following the steps below.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
