### ISSUE TITLE
Invoke-customs are only supported starting with android 0 --min-api 26

### ISSUE THREAD

**Issue by alfianyusufabdullah** [Rainbow-CPaaS/Rainbow-Android-SDK-Samples#4]
when i try to run my project i get some error like this

`Invoke-customs are only supported starting with android 0 --min-api 26`

why I get such an error and how to solve it ?

**Comment by letrongh** [comment]
Hello

The first thing I've found about your error is here: https://stackoverflow.com/a/50198499

Do you have that in your project? All three samples have, so they should work.

Nghia

**Comment by alfianyusufabdullah** [comment]
@letrongh I own it. its so my question why that error can happen & should use compileOption configuration?

**Comment by letrongh** [comment]
It seems like we need some Java 8 features but this is not specific to Rainbow.

See more here: https://developer.android.com/studio/write/java8-support

Have you tried with that?

**Comment by alfianyusufabdullah** [comment]
I've tried it and it works

Thank you for your time @letrongh
