### ISSUE TITLE
A+ Bug Found

### ISSUE THREAD

**Issue by benchris921** [Rainbow-CPaaS/Rainbow-Android-SDK-Samples#6]
Incoming call never works.  Outgoing call is fully working, but incoming call is never working.

**Comment by zucher** [comment]
Hi @benchris921 , did you register the Android Push notification ? under the application dashboard dedicated to you application ?
Take a look into https://hub.openrainbow.com/#/documentation/doc/sdk/android/guides/Enabling_push_notifications for more details.

Thank you

**Comment by benchris921** [comment]
Hi @zucher ,   Sorry,  Actually incoming call feature works fine.  

But it requires both of RECORD_AUDIO and CAMERA permissions even I need only audio call feature.

Thank you
Benjamin
